server:
  port: 8080

spring:
  application:
    name: TimeBoard
  thymeleaf:
    cache: false
    enabled: true
    prefix: 'classpath:templates/'
    suffix: '.html'
  flyway:
    enabled: true
    baseline-on-migrate: true
    placeholder-prefix: $${
    locations: 'classpath:db/migration/common'
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/timeboard
    username: timeboard
    password: timeboard_password
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: false