server:
  port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: false

multitenancy:
  app:
    accounts:
      datasource:
        url: jdbc:postgresql://192.168.99.100:5432/accounts
        username: admin
        password: admin
        driverClassName: org.postgresql.Driver
        connectionTimeout: 20000
        maxPoolSize: 10
        idleTimeout: 300000
        minIdle: 10
        poolName: accounts-connection-pool